config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts do
    resources :comments
  end
  patch '/posts/:id/add_likes', to: 'posts#add_likes', as:'add_likes'
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/user/:id', to: 'users#show', as: 'show_user'
  end

  root to: "posts#index"
  resources :pets
  resources :species
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users

  get '/search', to: "posts#search"
  get '/about', to: "posts#about"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :pets, :dependent => :destroy
    has_many :posts, :dependent => :destroy
    has_many :comments
    validates_presence_of :name
    validates :bio, length: {maximum: 80}

    def pet_count
        self.pets.size
    end

    def species_count
        counts = Hash.new
        self.pets.each do |pet|
            if !counts[pet.species.name]
                counts[pet.species.name] = 1
            else
                counts[pet.species.name] += 1
            end
        end
        counts
    end

    def self.most_pets
        self.all.max_by{|user| user.pets.size}
    end

    def post_alert_criteria
        if self.posts.count != 0
            self.posts.last.created_at.strftime('%d').to_i - Time.now.strftime('%d').to_i
        else  
            0
        end
    end

    def last_post
        self.posts.last.created_at.strftime('%B %d %Y')
    end

    def no_pet
        self.pets.empty?
    end

    def complete_profile
        self.name.empty? || self.bio.empty? || self.image.empty?
    end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

    def new
        super
    end

    def create
        super
    end

    def update
        super
    end

    def sign_up_params    
        params.require(resource_name).permit(:email, :password, :password_confirmation, :name, :bio, :image)
    end

    def account_update_params
        params.require(resource_name).permit(:email, :password, :password_confirmation, :current_password, :name, :bio, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :destroy]
    layout "post"

    def index
        @users = User.all
    end 

    def show
        @user = User.find(params[:id])
        @comment = Comment.new 
    end 

    def new
        @user = User.new
    end 

    def edit 
    end

    def create
        @user = User.create(user_params)
        redirect_to @user
    end 

    def update 
        @user.update(user_params)
        redirect_to @user
    end

    def destroy
        @user.destroy
    end

    private

    def set_user
        @user = current_user
    end

    def user_params
        params.require(:user).permit(:name, :bio, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
    <div class="col-sm-12">
        <div class="well">
            <%= form_with model: @user do |f| %>
                <p><%= f.label :name %>
                <%= f.text_field :name %></p>
                <p><%= f.label :image %>
                <%= f.text_field :image %></p>
                <p><%= f.label :bio %>
                <%= f.text_area :bio %></p>
                <%= f.submit %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="row">
    <% @users.each do |user| %>
    <div class="col-sm-4">
        <div class="sm-profile-container">
            <% if user.image %>
              <%= image_tag user.image, class: "profile-img", alt:"Avatar"%>
            <% end %>
            <p><%= link_to user.name, user %></p>
            <p><%= user.bio %></p>
            <p>Number of pets: <%= user.pet_count %></p>
            <% user.species_count.each do |k, v| %>  
                    <p><%= k %>: <%= v %></p>
            <% end %>
        </div>
    </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1>Create a New User</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="row"> 
    <div class="col-sm-12">
        <div class="post-inner-box">
            <div class="col-sm-12">
                <% if @user.image %>
                    <%= image_tag @user.image, class: "post-img", alt:"Avatar"%>
                <% end %>
                <h2><%= @user.name %></h2>
                <% if @user.id == current_user.id %>
                    <div class="d-flex justify-content-between">
                        <span class="btn btn-primary">
                            <%= link_to 'Create Post', new_post_path, :class => "btn-primary" %> 
                        </span>
                        <span class="btn btn-info">
                            <%= link_to 'Add Pet', new_pet_path, :class => "btn-info" %> 
                        </span>
                        <span class="btn btn-warning">
                            <%= link_to "Edit Or Delete Profile", edit_user_registration_path, method: :get, :class => "btn-warning" %>
                        </span><br><br>
                    </div>
                <% end %>
            </div>
            
            <h5>Bio: <%= @user.bio %></h5><br>
            Pets: <% @user.pets.each do |pet| %>
                <p><%= pet.species.name %>: <%= link_to pet.name, pet %></p>
            <% end %><br>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-12">
        <% @user.posts.each do |post| %>
            <div class="post-inner-box">
                 <div class="post-comment-box">
                     <p><%= post.content %></p>
                </div> 
                <%= link_to post do %>
                    <%= image_tag post.image, class: "post-img" %>
                <% end %>
               
                <%= bootstrap_form_for [post, @comment], bootstrap: {layout: "vertical"} do |f| %>
                   <br><%= f.text_area :content, placeholder: "Add a comment...", bootstrap: {label: {hide: true}}, class: "input-text-area" %>          
                    <%= f.primary "Post Comment", bootstrap: {layout: "vertical"}%><br>
                <% end %>
                <div class="post-comment-box">
                    <h4>Comments</h4>
                    <% post.comments.each do |comment| %>                      
                        <p><%= comment.user.name %> said: <%= comment.content %></p>                    
                    <% end %>
                </div>
                <%= button_to "Like", add_likes_path(post), :method => :patch, :class => "btn btn-primary"  %> <h5>Likes: <%= post.likes %></h5>
            </div> 
        <% end %>
    </div>        
</div>