config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts do
    resources :comments
  end
  patch '/posts/:id/add_likes', to: 'posts#add_likes', as:'add_likes'
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/user/:id', to: 'users#show', as: 'show_user'
  end

  root to: "posts#index"
  resources :pets
  resources :species
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users

  get '/search', to: "posts#search"
  get '/about', to: "posts#about"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Good Pets</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>    
      /* Set black background color, white text and some padding */
      footer {
        background-color: #555;
        color: white;
        padding: 15px;
      }
    </style>
  </head>

  <body>
<nav class="navbar navbar-inverse"> 
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Good Pets", posts_path, class: "navbar-brand"%>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      
      <% if user_signed_in? %>
        <div class="navbar-brand">      
         <h5>Welcome, <%= current_user.name %></h5>
        </div>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
          <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
          <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
      <% end %>     
      </ul>

    </div>
  </div>
</nav>
  
<div class="container text-center">    
  <div class="row">
    <div class="col-sm-12">
          <%= yield %>     
    </div>
  </div>
</div>

    <footer class="container-fluid text-center footer">
        <a href="/posts">GoodPets</a>. By Emma Fewer and David Wisecarver
    </footer>
   
  </body>
</html>

app/views/layouts/nav_bar.html.erb
<nav class="navbar navbar-inverse">
<div class="container-fluid">
    <div class="navbar-header">
    <%= link_to "Good Pets", posts_path, class: "navbar-brand"%>
    </div>
    <div class="collapse navbar-collapse">
    <form class="navbar-form navbar-right" action="/search">
        <input class="form-control" name="q" type="text" placeholder="Search">
        <button class="btn btn-sm" type="submit">
        <span class="glyphicon glyphicon-search"></span>
        </button>
    </form>
        <% if user_signed_in? %>
            <div class="nav navbar-nav navbar-left">
                <p class="navbar-brand mb-2">Welcome, <%= current_user.name%></p>      
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to ' Profile', edit_user_registration_path, :class => "glyphicon glyphicon-user"%></li>
                <li><%= link_to ' Log-out', destroy_user_session_path, method: :delete, :class => "glyphicon glyphicon-log-out" %></li>
        <% else %>
                <li><%= link_to ' Log In', new_user_session_path, :class => "glyphicon glyphicon-log-in" %></li>
                <li><%= link_to ' Sign Up', new_user_registration_path, :class => "glyphicon glyphicon-user" %></li>
            </ul>
        <% end %>
    </div>
</div>
</nav>

app/views/layouts/post.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Good Pets</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>    
      /* Set black background color, white text and some padding */
      footer {
        background-color: #555;
        color: white;
        padding: 15px;
      }
    </style>
  </head>

  <body>

    <%= render template: "layouts/nav_bar" %>
    <div class="container text-center">    
      <div class="row" id="main_container">
        <%= render template: "layouts/sidebar" %>
          <div class="col-sm-9">
              <%= yield %>     
          </div>
        </div>
      </div>
    </div>

    <footer class="container-fluid text-center footer">
        <a href="/posts">GoodPets</a>. By Emma Fewer <%= link_to "[github] ", "https://github.com/emmafewer" %>and David Wisecarver <%= link_to "[github]", "https://github.com/dwisecar" %>
    </footer>
   
  </body>
</html> 

app/views/layouts/sidebar.html.erb
<nav id="sidebar">
    <div class="p-4 pt-5">
        <% if current_user.image %>
            <%= image_tag current_user.image, class: "img logo img-circle", alt:"Avatar"%>
        <% end %><br><br>
        <ul class="list-unstyled components mb-5">
            <li><%= link_to "View Profile", show_user_path(current_user)%></li>
            <li><%= link_to "View All Users", users_path %></li>
            <li><%= link_to "View All Pets", pets_path %></li>
            <li><%= link_to "How to Link Images", about_path %></li>
        </ul>
        <br><br>
        <% if current_user.complete_profile %>
        <div class="alert alert-warning fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            Aww! Your profile is incomplete. Please complete your profile
            <%= link_to "here", edit_user_registration_path(current_user) %>
        </div>
        <% end %>
        <% if current_user.no_pet %>
        <div class="alert alert-warning fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            Oh no! Looks like you have no pets<br>
            <%= link_to "Add a pet", new_pet_path %>
        </div>
        <% end %>
        <% if current_user.post_alert_criteria > 2 %>
        <div class="alert alert-warning fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>            
            You haven't posted since <%= current_user.last_post %> .. Post now!
        </div>
        <% end %>
        <br>
        <% if !Pet.all.empty? %>
            <h5>Did you know?!</h5>
            <p><%= link_to Pet.oldest.name, pet_path(Pet.oldest) %> is the oldest pet at <%= Pet.oldest.age %>!</p>
            <p><%= link_to Pet.youngest.name, pet_path(Pet.youngest) %> is the youngest pet at <%= Pet.youngest.age %>!</p>
            <p><%= link_to User.most_pets.name, user_path(User.most_pets) %> has the most pets at <%= User.most_pets.pet_count %>!</p>
            <p>Our class has the most <%= Pet.most_common_species %>s at <%= Pet.most_common_species_count.values.max %></p>
            <% if Pet.most_unique_species_count == 1 %>
                <p><%= Pet.most_unique_species.name %> is the only <%= Pet.most_unique_species.species.name %></p>
            <% end %>
            <% if Pet.name_count.values.max > 1 %>
                <p><%= Pet.most_common_name %> is the most common pet name</p>
            <% end %>
            <% if Pet.check_breed_count.keys != [""] && Pet.check_breed_count.values.max > 1 %>
                <p><%= Pet.most_common_breed %> is the most common breed</p>
            <% end %>
            <br><br>

            <h5>See what's up!</h5>
            <p>Checkout the <%= link_to "most popular post", post_path(Post.most_popular) %></p>
            <p>Give <%= link_to "this post", post_path(Post.least_popular) %> some love!</p>
            <p>Get in on <%= link_to "this convo!", post_path(Post.most_comments) %></p>
            <br><br>
            
            <% if Pet.birthdays_this_month != [] %>
                <h5>Birthdays this month!</h5>
                <% Pet.birthdays_this_month.each do |pet| %>
                    <p><%= pet.name %> has a birthday on <%= pet.birthdate.month %>/<%= pet.birthdate.day %> </p>
                <% end %>
            <% end %>
        <% end %>
    </div>
</nav>